version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/staticmukesh/aerospike_exporter
    steps:
       - checkout
       - run: echo "hello world"